# Generated by Django 2.1.7 on 2019-12-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Announce',
        ),
    ]
