# Generated by Django 2.1.7 on 2019-12-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0002_auto_20191215_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announce',
            name='visible',
        ),
        migrations.AddField(
            model_name='announce',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Hide'),
        ),
    ]
