# Generated by Django 2.1.7 on 2019-12-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0003_auto_20191215_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announce',
            name='hide',
        ),
    ]
