# Generated by Django 2.1.7 on 2019-12-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0004_remove_announce_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='created_on',
            field=models.DateTimeField(verbose_name='Created'),
        ),
    ]
