# Generated by Django 2.1.7 on 2019-12-15 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0005_auto_20191215_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='show_on',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='announce',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
