# Generated by Django 3.0 on 2019-12-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0008_auto_20191215_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announce',
            name='days',
        ),
        migrations.AddField(
            model_name='announce',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
