# Generated by Django 3.0 on 2019-12-15 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0009_auto_20191215_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
