# Generated by Django 3.0 on 2019-12-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0010_auto_20191215_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
