# Generated by Django 3.0 on 2019-12-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0012_auto_20191215_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, verbose_name='Email')),
                ('mobile', models.CharField(max_length=15, verbose_name='GSM')),
                ('firstname', models.CharField(blank=True, max_length=128, verbose_name='Prenom')),
                ('lastname', models.CharField(blank=True, max_length=128, verbose_name='Nom')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('want_sms', models.BooleanField(default=True, verbose_name='SMS?')),
                ('site', models.CharField(blank=True, max_length=128, verbose_name='Site')),
            ],
        ),
    ]
