# Generated by Django 3.0 on 2019-12-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0014_service_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Label'),
        ),
    ]
