# Generated by Django 3.0 on 2019-12-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0015_auto_20191216_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Description')),
                ('contacts', models.ManyToManyField(to='app_sirene.Contact')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
