# Generated by Django 3.0 on 2019-12-23 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0016_contactgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titre')),
                ('status', models.IntegerField(choices=[(0, 'N/A'), (1, 'Suspected'), (2, 'On going'), (3, 'Closed'), (4, 'Auto Closed')], default=0, verbose_name='Etat')),
                ('priority', models.IntegerField(choices=[(0, 'N/A'), (1, '1-Critical'), (2, '2-High'), (3, '3-Medium'), (4, '4-Low')], default=0, verbose_name='Priorite')),
                ('start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Debut')),
                ('duration', models.IntegerField(blank=True, default=0, null=True, verbose_name='Durée estimée')),
                ('message', models.CharField(max_length=400, verbose_name='Message')),
                ('send_email', models.BooleanField(default=True, verbose_name='Email')),
                ('send_sms', models.BooleanField(default=False, verbose_name='SMS')),
                ('start2', models.DateTimeField(blank=True, null=True, verbose_name='Start real')),
                ('duration2', models.IntegerField(blank=True, default=0, null=True, verbose_name='Durée réelle')),
                ('downtime2', models.IntegerField(blank=True, default=0, null=True, verbose_name='Downtime réelle')),
                ('priority2', models.IntegerField(choices=[(0, 'N/A'), (1, '1-Critical'), (2, '2-High'), (3, '3-Medium'), (4, '4-Low')], default=0, verbose_name='Priorite finale')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('notify_groups', models.ManyToManyField(to='app_sirene.ContactGroup')),
                ('services', models.ManyToManyField(to='app_sirene.Service')),
                ('sites', models.ManyToManyField(to='app_sirene.Site')),
            ],
        ),
    ]
