# Generated by Django 3.0 on 2019-12-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0017_incident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='incident',
            name='downtime2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Downtime réel'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='start2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bilan Début réel'),
        ),
    ]
