# Generated by Django 3.0 on 2019-12-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0019_auto_20191223_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['priority', 'start']},
        ),
        migrations.AlterField(
            model_name='incident',
            name='downtime2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bilan Downtime réel'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='duration2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bilan Durée réelle'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority2',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'P1 Critique'), (2, 'P2 Elevé'), (3, 'P3 Moyen'), (4, 'P4 Faible')], default=0, verbose_name='Bilan Priorite finale'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.IntegerField(choices=[(1, 'En cours'), (2, 'Terminé')], default=1, verbose_name='Etat'),
        ),
    ]
