# Generated by Django 3.0 on 2019-12-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0020_auto_20191223_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'P1 Critique'), (2, 'P2 Haute'), (3, 'P3 Moyenne'), (4, 'P4 Faible')], default=0, verbose_name='Priorite'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority2',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'P1 Critique'), (2, 'P2 Haute'), (3, 'P3 Moyenne'), (4, 'P4 Faible')], default=0, verbose_name='Bilan Priorite finale'),
        ),
    ]
