# Generated by Django 3.0 on 2019-12-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0021_auto_20191223_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='app_sirene.Contact'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'P1 - Critique'), (2, 'P2 - Haute'), (3, 'P3 - Moyenne'), (4, 'P4 - Faible')], default=0, verbose_name='Priorite'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority2',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'P1 - Critique'), (2, 'P2 - Haute'), (3, 'P3 - Moyenne'), (4, 'P4 - Faible')], default=0, verbose_name='Bilan Priorite finale'),
        ),
    ]
