# Generated by Django 3.0 on 2019-12-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0022_auto_20191227_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['lastname']},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='priority2',
        ),
        migrations.AlterField(
            model_name='incident',
            name='message',
            field=models.CharField(max_length=400, verbose_name='Description'),
        ),
    ]
