# Generated by Django 3.0 on 2019-12-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0023_auto_20191227_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='duration2',
        ),
    ]
