# Generated by Django 3.0 on 2019-12-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0024_remove_incident_duration2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='downtime2',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='start2',
        ),
        migrations.AddField(
            model_name='incident',
            name='downtime',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Durée réelle (cloture)'),
        ),
    ]
