# Generated by Django 3.0 on 2019-12-28 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0025_auto_20191227_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['lastname', 'firstname']},
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, 'N/A'), (1, 'Incident'), (2, 'Maintenance'), (3, 'Information')], default=1, verbose_name='Catégorie')),
                ('title', models.CharField(max_length=120, verbose_name='Titre')),
                ('status', models.IntegerField(choices=[(0, 'N/A'), (1, 'Planifié'), (2, 'En cours'), (3, 'Terminé')], default=2, verbose_name='Etat')),
                ('priority', models.IntegerField(choices=[(0, 'N/A'), (1, 'P1 - Critique'), (2, 'P2 - Haute'), (3, 'P3 - Moyenne'), (4, 'P4 - Faible')], default=0, verbose_name='Priorité')),
                ('start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Début')),
                ('duration', models.IntegerField(blank=True, default=0, null=True, verbose_name='Durée')),
                ('downtime', models.IntegerField(blank=True, default=0, null=True, verbose_name='Indisponibilité')),
                ('detail', models.CharField(max_length=400, verbose_name='Description')),
                ('send_email', models.BooleanField(default=True, verbose_name='Envoi de mail')),
                ('send_sms', models.BooleanField(default=False, verbose_name='Envoi de SMS')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Auteur')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('notify_groups', models.ManyToManyField(to='app_sirene.ContactGroup')),
                ('services', models.ManyToManyField(to='app_sirene.Service')),
                ('sites', models.ManyToManyField(to='app_sirene.Site')),
            ],
            options={
                'ordering': ['start', 'priority', 'category'],
            },
        ),
    ]
