# Generated by Django 3.0 on 2019-12-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0026_auto_20191228_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='detail',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Description'),
        ),
    ]
