# Generated by Django 3.0 on 2019-12-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0028_auto_20191228_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='hide',
        ),
        migrations.AddField(
            model_name='info',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Masquer'),
        ),
    ]
