# Generated by Django 3.0 on 2019-12-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0029_auto_20191228_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='info',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
