# Generated by Django 3.0 on 2019-12-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0030_auto_20191228_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announce',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='notify_groups',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='services',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='sites',
        ),
        migrations.DeleteModel(
            name='IncidentTemplate',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
