# Generated by Django 3.0 on 2019-12-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0031_auto_20191228_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['pk', 'lastname', 'firstname']},
        ),
        migrations.AddField(
            model_name='info',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Template'),
        ),
    ]
