# Generated by Django 3.0 on 2019-12-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0033_info_template_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='contact',
            name='want_email',
            field=models.BooleanField(default=True, verbose_name='SMS?'),
        ),
        migrations.AlterField(
            model_name='info',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Modèle'),
        ),
    ]
