# Generated by Django 3.0 on 2020-01-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sirene', '0036_auto_20200102_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created_on',
            field=models.DateTimeField(editable=False, verbose_name='Création'),
        ),
        migrations.AlterField(
            model_name='info',
            name='updated_on',
            field=models.DateTimeField(editable=False, verbose_name='Mise à jour'),
        ),
    ]
